blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/', views.post_list, name='posts'),
    path('posts/<username>/', views.user_posts, name='posts'),
    path('comments/', views.comments_list, name='comments_list'),
    path('', views.dashboard, name='dashboard'),
]

blog_server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('users/', views.users_list, name='users_list'),
    path('users/follow/<int:pk>/', views.follow_to_user, name='follow_to_user'),
    path('users/unfollow/<int:pk>/', views.unfollow_from_user, name='unfollow_from_user'),
    path('users/block/<username>/', views.block_user, name='block_user'),
    path('users/unblock/<username>/', views.unblock_user, name='unblock_user'),
    path('users/followed/', views.followed_to_list, name='followed_to_list'),
    path('users/followers/', views.followers_list, name='followers_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('', include('django.contrib.auth.urls')),
]

blog/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models


class Post(models.Model):
    message = models.TextField(blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    image = models.ImageField(upload_to='posts/%Y/%m/%d', blank=True)
    description = models.CharField(verbose_name='image description', max_length=400, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {} - {}'.format(self.author.username, self.message, self.image)

    def clean(self):
        if not (self.message or self.image):
            raise ValidationError("You must specify either text or image")


class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.author.username, self.text[:10])

blog/forms.py
from django import forms

from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-group", 'placeholder': "What's on your mind?"}), required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': "form-group"}), required=False)
    description = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-group", 'placeholder': "describe your photo"}), required=False)

    class Meta:
        model = Post
        fields = ['message', 'image', 'description']


class CommentAddForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Add comment"}))

    class Meta:
        model = Comment
        fields = ['text']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from users.models import User
from .forms import PostCreateForm, CommentAddForm
from .models import Post, Comment


@login_required
def dashboard(request):
    posts = Post.objects.exclude(author=request.user)
    user = request.user
    followed = user.followed.values_list('id', flat=True)
    posts = posts.filter(author__in=followed)
    comments = Comment.objects.all().order_by('-id')[:3]
    if request.method == 'POST':
        comment_form = CommentAddForm(request.POST)
        post_form = PostCreateForm(request.POST, request.FILES)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return render(request, 'blog/dashboard.html', {'new_post': new_post})
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.save()
            return render(request, 'blog/dashboard.html', {'comment': new_comment})
    else:
        post_form = PostCreateForm()
        comment_form = CommentAddForm()
    context = {
        'section': 'dashboard',
        'posts': posts,
        'comments': comments,
        'post_form': post_form,
        'comment_form': comment_form
    }
    return render(request, 'blog/dashboard.html', context)


@login_required
def post_list(request):
    posts = Post.objects.filter(author=request.user)
    return render(request, 'blog/list.html', {'section': 'posts', 'posts': posts})


@login_required
def comments_list(request):
    comments = Comment.objects.all().order_by('-id')
    return render(request, 'blog/comments_list.html', {'comments': comments})


@login_required
def user_posts(request, username):
    user = User.objects.get_by_natural_key(username=username)
    posts = Post.objects.filter(author=user)
    return render(request, 'blog/user_posts.html', {'user': user, 'posts': posts})

templates/blog/comments_list.html
{% extends "base.html" %}

{% block title %}Posts{% endblock %}

{% block content %}
    <h1>Posts</h1>
    <div>
        {% for comment in comments %}
            <div>
                {{ comment.author.username }}<br>
                {{ comment.text }}<br>
                {{ comment.created }}
                <hr>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}

    <div>
        <h3>Add new post</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ post_form.as_p }}
            <input class="btn btn-info" type="submit" value="Post">
        </form>
    </div>
    <div>
        <h3>What's happening</h3>
        <div>
            <ul>
                {% for post in posts %}
                    <li>
                        {{ post.author }}<br>
                        {{ post.message }}<br>
                        {% if post.image %}
                            <img src="{{ post.image.url }}" alt="no-image"><br>
                        {% endif %}
                        {{ post.description }}
                    </li>
                    <hr>
                    <h6>Comments</h6>
                    {% for comment in comments %}
                        <p><small><a
                                href="{% url 'users:user_detail' comment.author.username %}">{{ comment.author }}</a></small>
                        </p>
                        <p>{{ comment.text }}</p><br>
                    {% endfor %}
                    <a href="{% url 'blog:comments_list' %}">More comments</a>
                    <form action="." method="post">
                        {% csrf_token %}
                        {{ comment_form.as_table }}
                        <input type="submit" class="btn btn-info" value="Add">
                    </form>
                    <hr>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}New Post created{% endblock %}

{% block content %}

    <h2>New Post created</h2>
    <div>
        {{ new_post.message }}<br>
        {% if new_post.image %}
            <img src="{{ new_post.image.url }}" alt=""><br>
        {% endif %}
        {{ new_post.description }}
    </div>

{% endblock %}

templates/blog/list.html
{% extends "base.html" %}

{% block title %}Posts{% endblock %}

{% block content %}
    <h1>Posts</h1>
    <div>
        {% for post in posts %}
            <div>
                {{ post.author.username }}
                {{ post.message }}
                {% if post.image %}
                    <img src="{{ post.image.url }}" alt="">
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/user_posts.html
{% extends "base.html" %}

{% block title %}{{ user.username }} posts{% endblock %}

{% block content %}
    <h1>{{ user.username }} posts</h1>
    <div>
        {% for post in posts %}
            <div>
                {{ post.message }}<br>
                {% if post.image %}<br>
                    <img src="{{ post.image.url }}" alt="">
                {% endif %}
                {{ post.description }}
                <hr>
            </div>
        {% endfor %}
    </div>
{% endblock %}