blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/', views.post_list, name='posts'),
    path('posts/<username>/', views.user_posts, name='posts'),
    path('comments/', views.comments_list, name='comments_list'),
    path('', views.dashboard, name='dashboard'),
]

blog_server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('users/', views.users_list, name='users_list'),
    path('users/follow/<int:pk>/', views.follow_to_user, name='follow_to_user'),
    path('users/unfollow/<int:pk>/', views.unfollow_from_user, name='unfollow_from_user'),
    path('users/block/<username>/', views.block_user, name='block_user'),
    path('users/unblock/<username>/', views.unblock_user, name='unblock_user'),
    path('users/followed/', views.followed_to_list, name='followed_to_list'),
    path('users/followers/', views.followers_list, name='followers_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('', include('django.contrib.auth.urls')),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(unique=True)
    followed = models.ManyToManyField('self', related_name='followers', symmetrical=False, blank=True)
    blocked = models.ManyToManyField('self', related_name='blockers', symmetrical=False, blank=True)
    profile_picture = models.ImageField(upload_to='users/', blank=True)

users/forms.py
from django import forms
from .models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'profile_picture']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']

    def clean_email(self):
        emails = User.objects.values_list('email', flat=True)
        email = self.cleaned_data['email']
        if email in emails:
            raise forms.ValidationError("This email already registered.")
        return email

users/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from blog.models import Post
from .forms import UserRegistrationForm
from .models import User


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST, request.FILES)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'users/register_done.html', {'news_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'users/register.html', {'user_form': user_form})


@login_required
def users_list(request):
    users = User.objects.exclude(blocked=request.user)
    return render(request, 'users/users_list.html', {'users': users})


@login_required
def user_detail(request, username):
    try:
        user = User.objects.get(username=username)
        posts = Post.objects.filter(author=user)
    except User.DoesNotExist:
        return HttpResponse('User not found')
    return render(request, 'users/user_detail.html', {'user': user, 'posts': posts})


@login_required
def followers_list(request):
    try:
        followers = User.objects.get(id=request.user.id).followers.all()
    except User.DoesNotExist:
        return HttpResponse('Nobody')
    return render(request, 'users/followers_list.html', {'followers': followers})


@login_required
def followed_to_list(request):
    try:
        followed_tos = User.objects.get(id=request.user.id).followed.all()
    except User.DoesNotExist:
        return HttpResponse('Nobody')
    return render(request, 'users/followed_to_list.html', {'followed_tos': followed_tos})


@login_required
def follow_to_user(request, pk):
    user = User.objects.get(id=request.user.id)
    user_to_follow = User.objects.get(id=pk)
    user.followed.add(user_to_follow)
    return redirect('users:users_list')


@login_required
def unfollow_from_user(request, pk):
    user = User.objects.get(id=request.user.id)
    user_to_unfollow = User.objects.get(id=pk)
    user.followed.remove(user_to_unfollow)
    return redirect('users:users_list')


@login_required
def block_user(request, username):
    user = User.objects.get(id=request.user.id)
    user_to_block = User.objects.get(username=username)
    user.blocked.add(user_to_block)
    return redirect('users:user_detail', username)


@login_required
def unblock_user(request, username):
    user = User.objects.get(id=request.user.id)
    user_to_unblock = User.objects.get(username=username)
    user.blocked.remove(user_to_unblock)
    return redirect('users:user_detail', username)

templates/users/followed_to_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Followed{% endblock %}

{% block content %}

    <h2>Followed users</h2>
    <div>
        {% for user in followed_tos %}
            <div>
                <img src="{% thumbnail user.profile_picture 50x50 crop %}" alt=""/>
                {% if user.first_name %}
                    {{ user.first_name }}
                {% endif %}
                {% if user.last_name %}
                    {{ user.last_name }}
                {% endif %}
                <br>
                <a href="{% url 'users:user_detail' user.username %}"><small>@{{ user.username }}</small></a><br>
                {% if user.posts.last != None %}
                    {{ user.posts.last }}
                {% endif %}
                {% if user.posts.last.image %}
                    <img src="{{ post.image.url }}" alt="">
                {% endif %}

                {% if request.user not in user.followers.all %}
                    <a href="{% url 'users:follow_to_user' user.id %}">Follow</a>
                {% else %}
                    <a href="{% url 'users:unfollow_from_user' user.id %}">Unfollow</a>
                {% endif %}
                <hr>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/users/followers_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Followers{% endblock %}

{% block content %}

    <h2>Followers</h2>
    <div>
        {% for user in followers %}
            <div>
                <img src="{% thumbnail user.profile_picture 50x50 crop %}" alt=""/>
                {% if user.first_name %}
                    {{ user.first_name }}
                {% endif %}
                {% if user.last_name %}
                    {{ user.last_name }}
                {% endif %}
                <br>
                <a href="{% url 'users:user_detail' user.username %}"><small>@{{ user.username }}</small></a><br>
                {% if user.posts.last != None %}
                    {{ user.posts.last }}
                {% endif %}
                {% if user.posts.last.image %}
                    <img src="{{ post.image.url }}" alt="">
                {% endif %}

                {% if request.user not in user.followers.all %}
                    <a href="{% url 'users:follow_to_user' user.id %}">Follow</a>
                {% else %}
                    <a href="{% url 'users:unfollow_from_user' user.id %}">Unfollow</a>
                {% endif %}
                <hr>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Create my account">
    </form>
{% endblock %}

templates/users/register_done.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ news_ser.first_name }}!</h1>
    <p>Your account has been successfully created. You can <a href="{% url 'users:login' %}">log in</a>.</p>
{% endblock %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% block title %}{{ user.username }} - details{% endblock %}

{% block content %}

    {% if user.profile_picture %}
        <img src="{{ user.profile_picture.url }}" alt=""><br>
    {% endif %}

    <h2>User: {{ user.username }}</h2>

    <div>
        {% if user.first_name %}
            <p><small>First name: </small>{{ user.first_name }}</p>
        {% endif %}
        {% if user.last_name %}
            <p><small>Last name: </small>{{ user.last_name }}</p>
        {% endif %}
        <br>
        {% if user.posts.last.image %}
            <img src="{{ post.image.url }}" alt="">
        {% endif %}
        {% if user.posts.last != None %}
            <p><small>Last post: </small>{{ user.posts.last }}</p>
            <a href="{% url 'blog:posts' user %}">More posts...</a>
        {% endif %}
        <hr>
        {% if request.user not in user.blockers.all %}
            <a href="{% url 'users:block_user' user.username %}">Block</a>
        {% else %}
            <a href="{% url 'users:unblock_user' user.username %}">Unblock</a>
        {% endif %}
    </div>

{% endblock %}

templates/users/users_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Posts{% endblock %}

{% block content %}

    <h2>Users</h2>
    <div>
        {% for user in users %}
            <div>
                <img src="{% thumbnail user.profile_picture 50x50 crop %}" alt=""/>
                {% if user.first_name %}
                    {{ user.first_name }}
                {% endif %}
                {% if user.last_name %}
                    {{ user.last_name }}
                {% endif %}
                <br>
                <a href="{{ user.username }}"><small>@{{ user.username }}</small></a><br>
                {% if user.posts.last != None %}
                    {{ user.posts.last }}
                {% endif %}
                {% if user.posts.last.image %}
                    <img src="{{ post.image.url }}" alt="">
                {% endif %}

                {% if request.user not in user.followers.all %}
                    <a href="{% url 'users:follow_to_user' user.id %}">Follow</a>
                {% else %}
                    <a href="{% url 'users:unfollow_from_user' user.id %}">Unfollow</a>
                {% endif %}
                <hr>
            </div>
        {% endfor %}
    </div>

{% endblock %}